---
- name: Install Nginx Ingress Controller
  include_tasks: "{{ playbook_dir }}/tasks/k8s/create.yaml"
  vars:
    name: ingress-nginx.yaml
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.0/deploy/static/provider/baremetal/deploy.yaml
