---
- name: Install Calico Pod Network
  include_tasks: "{{ playbook_dir }}/tasks/k8s/create.yaml"
  vars:
    name: calico.yaml
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml

- name: Install calicoctl for kubectl
  get_url:
    url: https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64
    dest: "{{ install_path }}"
    mode: 755
  vars:
    binary: kubectl-calico
    install_path: "/usr/local/bin/{{ binary }}"
